@echo off
rem part of TEST procedure of SWAP3.2
del/q   result.*
del/q   fort.*
del/q   *.aun
del/q   *.afo
del/q   *.bfo
del/q   *.blc
del/q   *.bak
del/q   *.bal
del/q   *.bun
del/q   *.csv
del/q   *.dat
del/q   *.dwb
del/q   *.end
del/q   *.inc
del/q   *.log
del/q   *.out
del/q   *.png
del/q   *.res
del/q   *.sba
del/q   *.snw
del/q   *.tmp
del/q   *.vap
del/q   *.wba
del/q   swap.ok
del/q   PerformIndex.tex
del/q   Waterbalans.tex
rem exit
